# Generated by Django 5.0.3 on 2026-04-17 16:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.CharField(db_index=True, max_length=100)),
                ('event_type', models.CharField(choices=[('view', 'Item View'), ('search', 'Item Search'), ('purchase_normal', 'Normal Item Purchase'), ('purchase_limited', 'Limited Item Purchase')], db_index=True, max_length=50)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'event_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
